### ISSUE TITLE
Persian Translate

### ISSUE THREAD

**Issue by Mehdi-MosTafavi** [ncase/covid-19#1]
Hi
I'm translating this project to Persian. (first, I had a problem with RTL, now it fixed)
If you want to help me, this is my fork: https://github.com/Mehdi-MosTafavi/covid-19
And I need some help for images :)

**Comment by pourdamghani** [comment]
@Mehdi-MosTafavi Hey Mehdi,
Let's get in touch with me, I want to offer few corrections on writings, and based on the state you are in, maybe help in the translation itself. Contact me via [myGithubID]@gmail if you like to.
Anyhow, tnx for stepping up and do the translation to this stage.
