### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by blurayfin** [ncase/covid-19#11]
https://github.com/blurayfin/covid-19

**Comment by akaralar** [comment]
@blurayfin gelisme var mi? yardim lazim mi? fork'ta issueler kapali oldugu icin oraya yazamadim, bir de commit de goremedim

**Comment by blurayfin** [comment]
> @blurayfin gelisme var mi? yardim lazim mi? fork'ta issueler kapali oldugu icin oraya yazamadim, bir de commit de goremedim

Ben ilgilenemedim. Siz devralabilir misiniz?

**Comment by akaralar** [comment]
sen bu issue'yu kapatabilir misin? yenisiyle acarim ben de

**Comment by blurayfin** [comment]
> sen bu issue'yu kapatabilir misin? yenisiyle acarim ben de

kapattım.
