### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by TQueV** [ncase/covid-19#12]
Link to forked repo: https://github.com/TQueV/covid-19

**Comment by jkoelling** [comment]
@TQueV 
Hey there, I'd love to help with the translation. What's your plan and how far are you so far? I've some time today and tomorrow in which I could translate quite a big chunk if not all of it, but I of course don't want to replicate any work you already did.  I don't see any commits on your fork yet.

btw, I translated Nicky's game of trust, so I've done this before: https://github.com/jkoelling/trust

Looking forward to hearing back from you soon. If I don't I'll start translating from the end and let you know what I've done via PRs on your repo.

**Comment by jkoelling** [comment]
@TQueV The french translation has a nice overview to split up the work. I'll be out with my dog now and create something similar (or simply copy the same) when I'm back. Feel free to do so yourself: https://github.com/cyrilou242/covid-19/blob/master/FRENCH_TRAD_NOTES.md

**Comment by TQueV** [comment]
@jkoelling 
Hey there, sorry for the late reply. Just do as much as you want, I'll be coming back to you in about 1h. Thanks!

**Comment by TQueV** [comment]
@jkoelling 
Sorry, took me even longer. So basically, I'm completely new to GitHub and just thought this projects needs to have a translation and it's an opportunity for me to get into this thing here. If you want to,i'll give you ownership of the repo.

**Comment by jkoelling** [comment]
You can keep the repo, we can work together on this. 

I opted for boardgames instead of starting on the translation so I'll get back to it tomorrow morning. 

We should set up a table as I've mentioned above to coordinate who does what. I'm happy to help you get started on your first project here. :)

**Comment by jkoelling** [comment]
Until we have a better overview, I suggest that we just make sure to mention here what we are working on and to push to github frequently.

**Comment by widomattern** [comment]
I would like to support you with the German translation, how can I help?

**Comment by TQueV** [comment]
> @TQueV The french translation has a nice overview to split up the work. I'll be out with my dog now and create something similar (or simply copy the same) when I'm back. Feel free to do so yourself: https://github.com/cyrilou242/covid-19/blob/master/FRENCH_TRAD_NOTES.md

So I made a basic overview text based on the French version: https://github.com/TQueV/covid-19/blob/master/GERMAN_TRANSL_NOTES
As you can see, it's still plain text (and I'm a complete newbie), so if you want, you can start by fixing that, @widomattern 

As the file should tell, I started by translating L1-L23 and won't continue after I got some sleep.

**Comment by widomattern** [comment]
Please rename the file "GERMAN_TRANSL_NOTES" to "GERMAN_TRANSL_NOTES.md", then it is no longer plain text.

**Comment by dotob** [comment]
hi, 
i would also like to help. what is your plan?

@TQueV it might be helpful to add some collaborators (@widomattern @jkoelling ) on the repo? 

perhaps a chat somewhere might also help. this should be done quickly dont you think?

**Comment by widomattern** [comment]
I have made my own fork (for now) https://github.com/widomattern/covid-19 and translated first sections. But I would (in the future) rather work on the German translation in a common fork.

**Comment by eBildungslabor** [comment]
Hi,
I also would like to help and just started with the intro. I have time to continue today. It would be great to have the translation quickly.
Nele

**Comment by eBildungslabor** [comment]
May be it is helpful for words.md to have the possibility to work synchroniously on it. Here would be a [CodiMD](https://hackmd.okfn.de/oU3YSW4aRQqEYrpBW7a_Rw?both#) for this. We coulkd copy it in Github later on.
@widomattern

**Comment by widomattern** [comment]
I am now working on "LastMonths: Curves" via [CodiMD](https://hackmd.okfn.de/oU3YSW4aRQqEYrpBW7a_Rw?both#)

**Comment by eBildungslabor** [comment]
I am now working on 'The next few month' via [CodoMD](https://hackmd.okfn.de/oU3YSW4aRQqEYrpBW7a_Rw?both#)

**Comment by eBildungslabor** [comment]
@jkoelling @dotob and @TQueV 
There is a [CodiMD](https://hackmd.okfn.de/oU3YSW4aRQqEYrpBW7a_Rw?both#) for translating words.md together and synchronously. @widomattern and me are working right now on it. See above for more information.

**Comment by TQueV** [comment]
I invited @eBildungslabor @widomattern and @jkoelling as contributors on the repo

**Comment by widomattern** [comment]
I have finished the first pass with "LastMonths: Curves"

**Comment by jkoelling** [comment]
I like the collaborative translating via CodiMD and and will use that too. 
We should make sure to commit somewhere before we start reviewing/editing translations so that we have a proper history of those changes (unless Codi support that somehow too?).

We should keep in mind, that the translation needs to be consistent. For that it would help to make a lit of repeating phrases across the original and then later check if we used the same translation everywhere. 

Also, Nick's texts are typically very careful to be inclusive (for example, not to gender specific). Translating to German makes this more complicated but we should try to stay as close in style and tone to the original and that includes inclusive language. 

I agree that it would be great to get this done quickly, but I also want this to be a translation that stays true to the original. I think we owe this to the creators if they link directly from their piece.

**Comment by jkoelling** [comment]
@widomattern @TQueV @eBildungslabor @dotob 
If you like you can join me on gitter: https://gitter.im/ncase-covid-19-translators/german

**Comment by dotob** [comment]
hi,
i am also in the chat. great way to collaborate. 

i will have a look at the pics now. the idea was to start image translation also in the codimd file at the end. so we have a good translation in text before editing the images.

**Comment by jkoelling** [comment]
I will start working on "The next few years" in Codi now.

@widomattern If you're done with a first pass, I suggest to commit it to the fork.

**Comment by jkoelling** [comment]
People are converging on CodiMD and the gitter chat. Please join if you want to contribute.

**Comment by tpo** [comment]
Bin auch dran im CodiMD am übersetzen (und Übersetzungen am fixen)

**Comment by jahfaby** [comment]
Joining now.
