### ISSUE TITLE
Translation in pictures (png)

### ISSUE THREAD

**Issue by NicoKiaru** [ncase/covid-19#15]
Hi! 

Amazing job @ncase (as usual...) ! 
How should we proceed to translate the text in the pictures ? Do you have some editable files ? Otherwise, what's the font ?

For anybody reading this, in the french fork by @cyrilou242 there's a document to prepare the text, even if we don't know how to edit the pictures yet : https://github.com/cyrilou242/covid-19/blob/master/pics/PICS_TRANSLATION.md

**Comment by NicoKiaru** [comment]
For those wandering around in this issue : many pictures have already been translated here:

https://github.com/DP-3T/documents/tree/master/public_engagement/cartoon

**Comment by simonefalcini** [comment]
I created a zip file with all the pics in PSD format ready to be edited:
[pics-psds.zip](https://github.com/ncase/covid-19/files/4577616/pics-psds.zip)

**Comment by dotob** [comment]
in the german version there are all pics with the texts removed: https://github.com/TQueV/covid-19/tree/master/pics/notext
may be a good start for e new translation.

we used mostly comic sans as a font

**Comment by sylvainberube** [comment]
The original font are Open Sans and Patrick Hand.
