### ISSUE TITLE
Greek Translation

### ISSUE THREAD

**Issue by estamos** [ncase/covid-19#28]
Link to to my repo : https://github.com/estamos/covid-19

Language : Greek (Modern Greek) | el 
Country : Hellenic Republic | Greece

Start date : 03-04-20
ETA : 10-05-20

Any help for image translation is welcome.

**Comment by xmac11** [comment]
Hey @estamos, I'd love to help with the translation. If that's ok with you, please let me know so I can undertake some parts.

**Comment by estamos** [comment]
> Hey @estamos, I'd love to help with the translation. If that's ok with you, please let me know so I can undertake some parts.

Hey @xmac11 , I have already finished translation of [`sim/index.html`](https://github.com/estamos/covid-19/blob/master/sim/index.html) and a big part of [`words.md`](https://github.com/estamos/covid-19/blob/master/words/words.md). You can help translating the remaining part of `words.md` or/and with [`/pics`](https://github.com/estamos/covid-19/tree/master/pics).

I am paying a lot of attention to the correct terminology of the translation and that's the reason ETA is quite long future.

**Comment by xmac11** [comment]
Thanks for the reply @estamos! 
Ok great! I'll continue with the `words.md` and try my best. Of course you can correct anything you don't like. I'll fork your repo and will be opening pull requests after small chunks are finished.
I can continue from where you left 

> It's a paradox [...] (L.213) 

up to

> So, what, do we just lockdown again & again? (L.331)

Perhaps we could also create a small document, or just use this place to tell what we are working on, so that our work doesn't collide.

**Comment by estamos** [comment]
Some remarkable notes about translation in Greek : 

1.  COVID-19 it's a disease so the correct translation is
η COVID-19 και όχι ο COVID-19
οξεία αναπνευστική νόσος 2019-nCoV

2. SARS-CoV-2 is a virus
κορονοϊός (ορθότερο του κοροναϊός)
προσοχή υπάρχουν πολλά είδη κορονοϊών
κορονοϊός σοβαρού οξέος αναπνευστικού συνδρόμου τύπου 2

**Comment by xmac11** [comment]
Hey @estamos, do you mind enabling Issues on your forked repo? I guess it might be more flexible coordinating from there than writing everything here. [Here's how you can do it](https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork).

**Comment by estamos** [comment]
> Hey @estamos, do you mind enabling Issues on your forked repo? I guess it might be more flexible coordinating from there than writing everything here. [Here's how you can do it](https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork).

done!

**Comment by sofiamagk** [comment]
Καλησπέρα! I can also help if help is desired.

**Comment by estamos** [comment]
> Καλησπέρα! I can also help if help is desired.

Καλησπέρα σας, βεβαίως κάθε βοήθεια είναι ευπρόσδεκτη. 
Η μετάφραση αφορά το [`words.md`](https://github.com/estamos/covid-19/blob/master/words/words.md), ένα μεγάλο κομμάτι της οποίας έχει ολοκληρωθεί.

**Comment by xmac11** [comment]
Καλησπέρα @sofiamagk, έχω ανοίξει ένα [issue](https://github.com/estamos/covid-19/issues/2) για να προσπαθήσουμε να οργανώσουμε τα κομμάτια που δουλεύουμε. Μπορείς να αναλάβεις κάποιο κομμάτι που δεν το δουλεύει κανείς.
Εκεί υπάρχει κι ένα Google Doc για να έχουμε μια ομοιομορφία στη μετάφραση.

@estamos Μιας κι έχει περάσει καιρός, σου έχει έρθει ειδοποίηση για το παραπάνω και το PR?

**Comment by estamos** [comment]
@xmac11 @sofiamagk 
Λόγω φόρτου εργασίας δεν μπορώ να συμβάλλω αρκετά στην συνέχιση της μετάφρασης , ωστόσο μόλις βρω λίγο ελεύθερο χρόνο ευχαρίστως να βοηθήσω περαιτέρω .

**Comment by xmac11** [comment]
> @xmac11 @sofiamagk
> Λόγω φόρτου εργασίας δεν μπορώ να συμβάλλω αρκετά στην συνέχιση της μετάφρασης , ωστόσο μόλις βρω λίγο ελεύθερο χρόνο ευχαρίστως να βοηθήσω περαιτέρω .

Κανένα πρόβλημα, αλίμονο! Απλά καλό είναι όποτε βρίσκεις χρόνο να γίνονται τουλάχιστον merge τα PRs, για να παίρνουμε όλοι την τελευταία έκδοση, και να κοιτάμε για πράγματα που μπορεί να έχουν ξεφύγει (ορθογραφικά κτλ).

**Comment by sofiamagk** [comment]
Καλημέρα! 

Οπότε να κάνω απλώς ένα git checkout και να σας πω ποιο κομμάτι θα ξεκινήσω? Ενδιαφέρει ακόμα το words.md; Πέρασε λίγος καιρός από τότε που σας έγραψα.

**Comment by xmac11** [comment]
Καλησπέρα, το [link](https://xmac11.github.io/covid-19/) της μετάφρασης είναι πλέον λάιβ, και συνδεδεμένο με το αγγλικό άρθρο, οπότε αυτό το issue μπορεί να κλείσει.

Υπολείπονται οι μισές εικόνες, τις οποίες δουλεύω και να ενσωματωθούν οι αλλαγές που έγιναν στο αγγλικό άρθρο αφότου ξεκινήσαμε τη μετάφραση.

Η μεγαλύτερη ανάγκη τώρα, σε περίπτωση που θέλει κάποιος να βοηθήσει, είναι για proofreading, κάτι που δεν έχω κάνει σχεδόν καθόλου, οπότε σίγουρα θα υπάρχουν και λάθη και περιθώρια βελτίωσης.
Και φυσικά να φτάσει σε ανθρώπους να το διαβάσουν. :wink:
