### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by harisont** [ncase/covid-19#3]
Hi! I am willing to help translate this amazing work to Italian, **but** I'll not be as fast as I'd like to, so I would really appreciate if someone could help with images etc. (well, whatever isn't in `words.md`).

[Here](https://github.com/harisont/covid-19) is my fork. Will probably start in 2-3 days.

**Comment by mendaomn** [comment]
Would love to help out!

**Comment by harisont** [comment]
Great! I made you a collaborator on my fork so you can push there directly, if that works better.

**Comment by rubinogiov** [comment]
Happy to help with the images.

**Comment by bianca-ambrogina** [comment]
Hi, I'd be happy to help with proof-reading if needed.

**Comment by martinowong** [comment]
happy to help with images and text too

**Comment by pietroppeter** [comment]
Hi, I did add a [pull request](https://github.com/harisont/covid-19/pull/1) to your repo with some translation and maybe it is also useful because the markdown parsing is not as smooth as I though it was. Hopefully, I will be able to help more today or in the next few days.

**Comment by pietroppeter** [comment]
For the images [another issue](https://github.com/ncase/covid-19/issues/15) suggests that many translations can already be found here:

https://github.com/DP-3T/documents/tree/master/public_engagement/cartoon

**Comment by simonefalcini** [comment]
If you need help, I'll be happy to assist. How are we going to coordinate? :)

**Comment by harisont** [comment]
Thank you all for your help!
 @simonefalcini I think to coordinate you could create issues on my fork saying what you are about to do or doing, so we avoid doing the same things twice. If you have a better strategy in mind just let us know, though :)
@bianca-ambrogina I think you should feel free to read the translation as we write it if you want to give suggestions or make corrections, but your help will be appreciated even more if you could go through the whole "main text" (`words.md`) once finished, cause @pietroppeter is also working on it so I guess there will be some inevitable style clashes.
And by the way, thank you very much @pietroppeter! I'm going through your pull request right now and will start translating the text from where you stopped in minutes.

**Comment by harisont** [comment]
UPDATE: [Here](https://github.com/harisont/covid-19/issues/2) you can find an open issue where you can comment what you are working on, so that we all know.

**Comment by pietroppeter** [comment]
closed by #43
